[build]
  command = "npm run build"
  publish = "dist"


[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://land-regen-backend.onrender.com"
  VITE_SUPABASE_URL = "https://wogdqjmwwypqrgxlkamj.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvZ2Rxam13d3lwcXJneGxrYW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNDM2NTgsImV4cCI6MjA3NTYxOTY1OH0.qBO4Q4V-I2aPbFgwH-Yynh9T9DVAnZ03ypCMcGVO4zc"
